config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/actors')
  resources :actors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  include AlgoliaSearch
  algoliasearch do
    attributes :name, :alternative_name, :image_path, :rating
    searchableAttributes [:name, :alternative_name]
    customRanking ['desc(rating)']
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :rating, :image_path, :alternative_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/_form.html.erb
<%= form_for(actor) do |f| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :image_path %>
    <%= f.text_field :image_path %>
  </div>

  <div class="field">
    <%= f.label :alternative_name %>
    <%= f.text_field :alternative_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<form action="/actors/search">
  <input id="search-input" name="query" type="text" placeholder="Search for actors..."/>
</form>
<hr />


<h1>Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Image path</th>
      <th>Alternative name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.rating %></td>
        <td><%= actor.image_path %></td>
        <td><%= actor.alternative_name %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @actor.rating %>
</p>

<p>
  <strong>Image path:</strong>
  <%= @actor.image_path %>
</p>

<p>
  <strong>Alternative name:</strong>
  <%= @actor.alternative_name %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWorkshopLiveCoding</title>
    <%= csrf_meta_tags %>

    <script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.7/css/bootstrap.min.css" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>